// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDgjXtqJUdPuSBmo9XRDhVihchjeC7lU0',
    appId: '1:692748945212:web:c4207e70bf9a5ff1664039',
    messagingSenderId: '692748945212',
    projectId: 'minimal-social-app-a893c',
    authDomain: 'minimal-social-app-a893c.firebaseapp.com',
    storageBucket: 'minimal-social-app-a893c.appspot.com',
    measurementId: 'G-C041PPZZ31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbWPEY-GgB_wRg4IcmqU8JvJT3TkfLizQ',
    appId: '1:692748945212:android:1194b494d19a0afc664039',
    messagingSenderId: '692748945212',
    projectId: 'minimal-social-app-a893c',
    storageBucket: 'minimal-social-app-a893c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKbGIMPuvN1T25h5BFFYbDa19t-u9v19M',
    appId: '1:692748945212:ios:6b5ace80cfda912b664039',
    messagingSenderId: '692748945212',
    projectId: 'minimal-social-app-a893c',
    storageBucket: 'minimal-social-app-a893c.appspot.com',
    iosBundleId: 'com.example.minimalsocialtute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKbGIMPuvN1T25h5BFFYbDa19t-u9v19M',
    appId: '1:692748945212:ios:5f9ef2b5942156e6664039',
    messagingSenderId: '692748945212',
    projectId: 'minimal-social-app-a893c',
    storageBucket: 'minimal-social-app-a893c.appspot.com',
    iosBundleId: 'com.example.minimalsocialtute.RunnerTests',
  );
}
